# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 50d6abd53c7cb777cad4fad8f088f041c9ac2b3b58b7975fbd3665596c780159e1e3e0e221fbcc96aa3925ab9b419d3412328512ff24294d3cd972fc2d315966

test:
  secret_key_base: 5056cf36f5a2b0d0e78a72be1e176cfc2021b6ff2d2a7272fd9a9a4aa2e08e98a041984fefb97ae5c575235010f68ebc7f88bdb60f059756240a15bf623fb638

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
